config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'posts#index'
  
  resources :posts do
    resources :replies
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :replies, dependent: :destroy
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order("created_at DESC")
  end
  
  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  
  private
    
    def post_params
      params.require(:post).permit(:title, :content)
    end
    
    def find_post
      @post = Post.find(params[:id])
    end
  
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  
  def show
  end
  
  def create
    @post = Post.find(params[:post_id])
    @reply = @post.replies.create(params[:reply].permit(:reply))
    @reply.user_id = current_user.id if current_user
    @reply.save
    redirect_to @post
  end
  
  def edit
    @post = Post.find(params[:post_id])
    @reply = @post.replies.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:post_id])
    @reply = @post.replies.find(params[:id])
    if @reply.update(params[:reply].permit(:reply))
      redirect_to @post
    end
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @reply = @post.replies.find(params[:id])
    @reply.destroy
    redirect_to @post
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'></link>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "Forum", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Add Post", new_post_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete,
                              data: { confirm: "Are you sure?" } %></li>
      <% else %>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
  <% end %>  
  <div class="row">
    <div class="col-md-8">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>
  

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to "Cancel", @post %>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
  <h2><%= link_to p.title, p %></h2>
  <p>Posted <%= time_ago_in_words(p.created_at) %> ago by <%= p.user.email %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<h2><%= @post.replies.count %> Replies</h2>
<%= render @post.replies %>
<h3>Reply to thread:</h3>
<%= render 'replies/form' %>
<%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to "Delete", @post, method: :delete,
                             data: { confirm: "Are you sure?" } %> |
<%= link_to "Home", root_path %>                             

app/views/replies/_form.html.erb
<%= simple_form_for([@post, @post.replies.build]) do |f| %>
  <%= f.input :reply %>
  <%= f.submit %>
<% end %>

app/views/replies/_reply.html.erb
<%= reply.reply %>
<p>Reply by <%= reply.user.email %>
<%= link_to "Edit Reply", edit_post_reply_path(reply.post, reply) %>
<%= link_to "Delete Reply", [reply.post, reply], method: :delete,
                            data: { confirm: "Are you sure?" } %></p>

app/views/replies/edit.html.erb
<h1>Edit Reply</h1>
<%= simple_form_for([@post, @reply]) do |f| %>
  <%= f.input :reply %>
  <%= f.submit %>
<% end %>